pyms: 
  services:
    swagger:
      path: ""
      file: "infrastructure/swagger.yml"
      url: "/ws-doc/"
      project_dir: "src.cotrollers"
  config:
    DEBUG: false
    APP_NAME: meli-mutants
    APPLICATION_ROOT : ""
    CONNECTION_DATABASE: "postgresql://postgres:root@localhost/postgres"
    CACHE_HOST: 0.0.0.0
    CACHE_PORT: 11211
    CACHE_EXPIRATION_TIME: 86400
    DATABASE_TABLE_DNA: "dna"