pyms: 
  services:
    swagger:
      path: ""
      file: "infrastructure/swagger.yml"
      url: "/ws-doc/"
      project_dir: "src.cotrollers"
  config:
    DEBUG: false
    APP_NAME: meli-mutants
    APPLICATION_ROOT : ""
    CONNECTION_DATABASE: "postgresql://postgres:4N45Ep8NTrq@18.228.175.124/postgres"
    DATABASE_TABLE_DNA: "dna"