---
swagger: "3.0"
info:
  description: "Microservice to serve mutant"
  version: "1.0.0"
  title: "End Points list of mutant"
  termsOfService: "https://www.mercadolibre.com.co"
schemes:
  - "http"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"