version: "3.9"

services:
  microservice:
      image: henry512/api-meli-mutants:latest
      restart: always
      ports:
          - 5000:5000
      networks:
          - meli-mutants

networks:
    meli-mutants:
