version: "3.9"

services:
   microservice:
      image: henry512/api-meli-mutants:latest
      restart: always
      ports:
          - 5000:5000
      networks:
          - meli-mutants
   postgresql:
      image: postgres:14.1
      restart: always
      ports:
          - 5432:5432
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=4N45Ep8NTrq
          - POSTGRES_DB=default_database 
      networks:
          - meli-mutants


networks:
    meli-mutants:
